### ISSUE TITLE
Graph refresh upon edit

### ISSUE THREAD

**Issue by julianstanley** [julianstanley/gfpopgui#47]
Hi @tdhock, here's something Guillem and I discussed today that I need your help/input on. This is a pretty long post, so no rush responding--I still have other things to do before getting to this, so this isn't a bottleneck.

The fact that the graph refreshes when new edges are added is a huge annoyance.

Example of problem: 

![](https://imgur.com/61T5n0Z.gif)

With many nodes, this can be super disorienting. Guillem thinks that users could get used to it, but would be frustrated at first.

## Why does the graph need to refresh?

I need to refresh the graph whenever I want to send some data from R to HTML/JS.

Right now, that's important for three purposes:

(1) Setting default values for an edge.

(2) Validating that the parameters that the user gives are reasonable.

(3) Updating the pop-up "edit edge" window to have correct values after the user edits them.

A small part of this problem is a visNetwork bug--when you edit the penalty of an edge, the "edit edge" pop-up should reflect that change.
<details>
<summary>(Side Note)</summary>
The bug I described above is specific to when edges have "Inf" or "NA" values for one of their parameters--visNetwork can't handle those and will end up making _all_ values undefined when it sees one. Since we have Inf and NA values, I have to go through R and change those to strings before sending them to visNetwork, then convert them back to float when they're returned to R. That means the graph needs to refresh, like I describe below.
</details>

But most of it is a broader incompatibility with the way that visNetwork is designed:

The visNetwork canvas can't take any input from R without refreshing. So, if the graphdf changes, visNetwork needs to refresh to reflect that change. For example, if I want to send an "edit edge" command to R, have R check whether the "type" or "penalty" or etc of the edge is valid, R can't send that result back to visNetwork without a refresh. 

Or, if I want to construct the "label" of an edge as a concatenation of different edge parameters, I have the same problem.

To demonstrate this, here's an example of adding/editing edges, but manually refreshing:

![](https://imgur.com/RuJOleq.gif)

You can see that (1) everything is undefined when you make a new edge, (2) the edge label doesn't update, and (3) when you try to edit the penalty of the edge, the edge disappears!

## What are the potential solutions?

Some of these problems could be solved from visNetwork's end, but others are pretty specific to our--e.g. data validation. 

I can work more with visNetwork on this, but Guillem proposed a separate solution:

He thinks it might be easier to seperate the list of parameters from the visNetwork visualization. In that implementation, the visNetwork graph has nodes (with labels) and edges (with labels), and that's it. When you click a node/edge, the corresponding row in the gfpop graphdf (shown below the graph) is highlighted. Then you edit the parameters in that dataframe directly. 

I think I agree with him that that could be a good idea. The problems presented here are probably fixable (by modifying visNetwork.js)  but might take a while. His solution would be a lot faster, and might actually be the more practical implementation in a lot of cases--for example, if you want to quickly change the penalty in 4 different edges, clicking on each edge and clicking "edit", "save" individually is a bit tedious, but faster to just edit the dataframe directly.

So, the flow here would be: (1) draw the graph topology that you want in visNetwork, (2) tweak the parameters in the dataframe below the visNetwork graph, with cross-brushing between the dataframe and the network, (3) click checkboxes with how you want edges/nodes to be annotated, (4) option to export graph visualization and/or R code

But we both wanted to check with you to see if you had any thoughts/feedback on that!

**Comment by tdhock** [comment]
I agree that refresh is really dis-orienting, and we need to figure out a way to avoid that. Thanks for the helpful screencast.
1. is it possible to avoid the refresh by keeping all the data in the client/js code during the graph editing? so after each edit you do NOT do any interaction with R/server. Anyways we only need the server for computing the model.
2. is it possible to save the state of the the graph node positions etc and tell that to visnetwork if the refresh is necessary?
3. i think direct manipulation editing of the graph is a better user interface than indirect manipulation of the graph in a table of edges. would be nice if you could do BOTH though.
does that help?

**Comment by julianstanley** [comment]
After thinking about this more, I think I can work more on limiting the need to refresh (/ hit the server). I'll also post some issues to visNetwork to limit the need to hit the server in the first place. Here are specific responses:

> is it possible to avoid the refresh by keeping all the data in the client/js code during the graph editing? so after each edit you do NOT do any interaction with R/server. Anyways we only need the server for computing the model.

Yes, this is possible, but I think we'd need modifications to visNetwork for this, I think? Specifically:

1. visNetwork can't handle automatic edge labeling

If I want to automatically label edges with certain values (e.g. the type of the edge), we need a graph refresh.

_A less-desirable solution using the shiny server:_ Just don't label edges (or let users manually label edges), or just tell the users that they need to press the 'refresh' button to refresh their labels. I feel like I can do without edge labels until I'm done drawing the graph.

2. visNetwork doesn't have any data validation options

This might be a feature that other users want (e.g. optionally specify what values are acceptable in a given edge parameter) that we could work with visNetwork with.

Parts of this are a bit specific, though--for example, I'd also like my data validation to be case-insensitive--I can just read everything as lowercase (e.g. "UP" and "DOWN" are okay, I think)

_A less-desirable solution from the shiny server:_ Don't validate data entries at the visNetwork-level, but do send the user warning messages. So, when if a user puts in "absolute" as an edge type instead of "abs", visNetwork won't stop them, but they'll get a pop-up message telling them that they made a mistake. 

3. visNetwork can't handle Inf and missing values

E.g.:
```R
my_nodes <- data.frame(id = "Node", label = "Node")
my_edges <- data.frame(from = "Node", to = "Node", parameterA = 1, parameterB = Inf)

# Here, "parameters" is listed as undefined, not Inf.
visNetwork(my_nodes, my_edges) %>% 
    visOptions(manipulation = list(enabled = T, 
        editEdgeCols = c("parameterA", "parameterB")))
```

_A less-desirable solution from the shiny-server:_ Just change all Infs to strings before passing them to visNetwork, and change them back before sending to gfpop, I already do this.

All-in-all, I think I'm just going to implement the "Less-desirable solution from the shiny-server" for these points for now and mention the more-desirable solutions on the visNetwork repo if you think that's a good idea?

> is it possible to save the state of the graph node positions etc and tell that to visnetwork if the refresh is necessary?

Yes, I already do this. I need to update the documentation on this, but `modifyVisNetwork` (defined in [fct_visNetwork_helpers.R](modify_visNetwork)) returns a list with a boolean 'refresh' parameter. 

So, after modifying the current graph, I decide whether or not to refresh. It's just that, as-is, refreshes are often necessary--basically anytime an edge is added or modified.

> i think direct manipulation editing of the graph is a better user interface than indirect manipulation of the graph in a table of edges. would be nice if you could do BOTH though.

Yeah, I agree--por qué no los dos? I suppose porque el primera implementación es mas complicada que el segundo, but maybe these issues are surmountable.

> does that help?

Yep! Thanks!

**Comment by julianstanley** [comment]
^ when typing that, though, I forgot about default edges. thats a big one

When I make a new edge, I think I’d like it to be a null edge by default. Otherwise, I need to put in every edge parameter manually, which is a bit tedious. 

or, better yet, it would be great if the user could specify a ‘template’ for a new edge to start from—e.g up with a gap of 0.5. 

Not sure how to do that without hitting the server and thus needing a refresh in the current implementation. But maybe I can by adding a javascript snippet that triggers when the ‘add edge’ button is pressed that auto-fills those fields.

**Comment by tdhock** [comment]
can't you write some custom javascript code to do the data validation in browser? sounds like you should ask the visNetwork dev about that. I find it strange/annoying that we have to hit the server so much. in principle we should only need to hit the server for running gfpop. 
also for the null edges, again in most graphs I work with all nodes will have null edges so it is just annoying to have the user create all of them. instead would be preferable to just have null edges on all nodes by default (without showing them), and then have some check box that allows you to turn that off and create null edges yourself if you want more flexibility.

**Comment by julianstanley** [comment]
> can't you write some custom javascript code to do the data validation in browser? sounds like you should ask the visNetwork dev about that. I find it strange/annoying that we have to hit the server so much. in principle we should only need to hit the server for running gfpop.

Yeah, I need to get more comfortable with using JS inside Shiny. I'll work on this this week

> also for the null edges, again in most graphs I work with all nodes will have null edges so it is just annoying to have the user create all of them. instead would be preferable to just have null edges on all nodes by default (without showing them), and then have some check box that allows you to turn that off and create null edges yourself if you want more flexibility.

Yep, absolutely. This is also going to be tricky for me without hitting the server, but I'll give it a shot.

**Comment by julianstanley** [comment]
Just a small update

I was getting a bit frustrated with this--visNetwork is basically completely hidden from the dom (since it's canvas) and even the buttons are hard to get a hold of since they are generated by Shiny (renderVisNetwork-->visNetwork.js-->buttons are added to the dom). [Posted a StackOverflow post](https://stackoverflow.com/questions/62794827/r-shiny-run-js-after-htmlwidget-renders).

But a _lot_ of what I want to do here can actually be solved by [visNetworkProxy](https://datastorm-open.github.io/visNetwork/shiny.html). It's a bit silly that I didn't look more into this in the first place, actually, visNetworkProxy was designed for just this situation: updating the visNetwork plot without re-rendering and adding custom JS onto the plot. 

So, working on that now.

**Comment by tdhock** [comment]
great!
