### ISSUE TITLE
Refactor data.frame-->data.table

### ISSUE THREAD

**Issue by julianstanley** [julianstanley/gfpopgui#58]
Need to refactor a lot of my tables. I bet I can make things a bit more efficient with data.table, like Toby mentioned early on.

**Comment by julianstanley** [comment]
Oh, holy shit @tdhock , data.table is fantastic. I should've taken your advice sooner, this is so fast and so easy. I can delete my `mutate_cond` function. 

``` r
library(data.table)

my_table <- data.table(gfpop::graph(type = "updown"))

# Subset
my_table[type == "up"]
```

    ##    state1 state2 type parameter penalty   K a min max
    ## 1:     Dw     Up   up         0       0 Inf 0  NA  NA

``` r
# Replace row
my_table[, penalty := c(1,2,3,4)]

my_table
```

    ##    state1 state2 type parameter penalty   K a min max
    ## 1:     Dw     Dw null         1       1 Inf 0  NA  NA
    ## 2:     Up     Up null         1       2 Inf 0  NA  NA
    ## 3:     Dw     Up   up         0       3 Inf 0  NA  NA
    ## 4:     Up     Dw down         0       4 Inf 0  NA  NA

``` r
# Conditionally replace row
my_table[type == "up", penalty := 1000]

my_table
```

    ##    state1 state2 type parameter penalty   K a min max
    ## 1:     Dw     Dw null         1       1 Inf 0  NA  NA
    ## 2:     Up     Up null         1       2 Inf 0  NA  NA
    ## 3:     Dw     Up   up         0    1000 Inf 0  NA  NA
    ## 4:     Up     Dw down         0       4 Inf 0  NA  NA

**Comment by tdhock** [comment]
haha yes data.table is great
